basePath: /
definitions:
  ftgo-finpro_internal_adminStoreHandler_models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  ftgo-finpro_internal_adminStoreHandler_models.LoginResponse:
    properties:
      email:
        type: string
      name:
        type: string
      token:
        type: string
    type: object
  ftgo-finpro_internal_adminStoreHandler_models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      store_id:
        type: string
    required:
    - email
    - name
    - password
    - store_id
    type: object
  handler.FacilitatePurchaseRequest:
    properties:
      customer_id:
        type: string
      items:
        items:
          $ref: '#/definitions/handler.PurchaseItem'
        type: array
      payment_method:
        description: '"Wallet" or "Online"'
        type: string
    required:
    - customer_id
    - items
    - payment_method
    type: object
  handler.PurchaseItem:
    properties:
      product:
        type: string
      quantity:
        minimum: 1
        type: integer
    required:
    - product
    - quantity
    type: object
  handler.RecycleMaterialsRequest:
    properties:
      product:
        type: string
      quantity:
        minimum: 1
        type: integer
    required:
    - product
    - quantity
    type: object
  handler.RedeemTokenRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  models.VerifyCustomerRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
host: localhost:8080
info:
  contact:
    email: Obie.kal22@gmail.com
    url: www.linkedin.com/in/obie-ananda-a87a64212
  description: API documentation for the FTGO PlashCash project.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: FTGO PlasCash Project
  version: "1.0"
paths:
  /store-admin/login:
    post:
      consumes:
      - application/json
      description: Authenticates a store admin and returns a JWT token
      parameters:
      - description: Store admin login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ftgo-finpro_internal_adminStoreHandler_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ftgo-finpro_internal_adminStoreHandler_models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a store admin
      tags:
      - StoreAdmin
  /store-admin/purchase:
    post:
      consumes:
      - application/json
      description: Facilitates a purchase by deducting inventory and processing payment
        via wallet or online methods
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Purchase request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.FacilitatePurchaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Facilitate a purchase in a store
      tags:
      - StoreAdmin
  /store-admin/recycle/{customer_id}:
    post:
      consumes:
      - application/json
      description: Processes recycling requests from customers and updates vending
        machine status
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Customer ID
        in: path
        name: customer_id
        required: true
        type: string
      - description: Recycling request
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/handler.RecycleMaterialsRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Recycle materials into a vending machine
      tags:
      - StoreAdmin
  /store-admin/redeem-token/{customer_id}:
    post:
      consumes:
      - application/json
      description: Redeems a customer token and updates the wallet balance
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Customer ID
        in: path
        name: customer_id
        required: true
        type: string
      - description: Token redemption request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RedeemTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Redeem a token for wallet balance
      tags:
      - StoreAdmin
  /store-admin/register:
    post:
      consumes:
      - application/json
      description: Registers a new store admin with the provided details
      parameters:
      - description: Store admin registration request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ftgo-finpro_internal_adminStoreHandler_models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a store admin
      tags:
      - StoreAdmin
  /verify-customer:
    post:
      consumes:
      - application/json
      description: This endpoint verifies a customer by their email address.
      parameters:
      - description: Request body containing the customer's email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VerifyCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Customer verified successfully
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify a customer by email
      tags:
      - StoreAdmin
swagger: "2.0"
